default_command_dict = {
    "descriptors": {
        "MaxEStateIndex": {
            "command": ["MaxEStateIndex"],
            "column_names": ["_feat_MaxEStateIndex"],
        },
        "MinEStateIndex": {
            "command": ["MinEStateIndex"],
            "column_names": ["_feat_MinEStateIndex"],
        },
        "MaxAbsEStateIndex": {
            "command": ["MaxAbsEStateIndex"],
            "column_names": ["_feat_MaxAbsEStateIndex"],
        },
        "MinAbsEStateIndex": {
            "command": ["MinAbsEStateIndex"],
            "column_names": ["_feat_MinAbsEStateIndex"],
        },
        "qed": {"command": ["qed"], "column_names": ["_feat_qed"]},
        "MolWt": {"command": ["MolWt"], "column_names": ["_feat_MolWt"]},
        "HeavyAtomMolWt": {
            "command": ["HeavyAtomMolWt"],
            "column_names": ["_feat_HeavyAtomMolWt"],
        },
        "ExactMolWt": {"command": ["ExactMolWt"], "column_names": ["_feat_ExactMolWt"]},
        "NumValenceElectrons": {
            "command": ["NumValenceElectrons"],
            "column_names": ["_feat_NumValenceElectrons"],
        },
        "NumRadicalElectrons": {
            "command": ["NumRadicalElectrons"],
            "column_names": ["_feat_NumRadicalElectrons"],
        },
        "MaxPartialCharge": {
            "command": ["MaxPartialCharge"],
            "column_names": ["_feat_MaxPartialCharge"],
        },
        "MinPartialCharge": {
            "command": ["MinPartialCharge"],
            "column_names": ["_feat_MinPartialCharge"],
        },
        "MaxAbsPartialCharge": {
            "command": ["MaxAbsPartialCharge"],
            "column_names": ["_feat_MaxAbsPartialCharge"],
        },
        "MinAbsPartialCharge": {
            "command": ["MinAbsPartialCharge"],
            "column_names": ["_feat_MinAbsPartialCharge"],
        },
        "FpDensityMorgan1": {
            "command": ["FpDensityMorgan1"],
            "column_names": ["_feat_FpDensityMorgan1"],
        },
        "FpDensityMorgan2": {
            "command": ["FpDensityMorgan2"],
            "column_names": ["_feat_FpDensityMorgan2"],
        },
        "FpDensityMorgan3": {
            "command": ["FpDensityMorgan3"],
            "column_names": ["_feat_FpDensityMorgan3"],
        },
        "BalabanJ": {"command": ["BalabanJ"], "column_names": ["_feat_BalabanJ"]},
        "BertzCT": {"command": ["BertzCT"], "column_names": ["_feat_BertzCT"]},
        "Chi0": {"command": ["Chi0"], "column_names": ["_feat_Chi0"]},
        "Chi0n": {"command": ["Chi0n"], "column_names": ["_feat_Chi0n"]},
        "Chi0v": {"command": ["Chi0v"], "column_names": ["_feat_Chi0v"]},
        "Chi1": {"command": ["Chi1"], "column_names": ["_feat_Chi1"]},
        "Chi1n": {"command": ["Chi1n"], "column_names": ["_feat_Chi1n"]},
        "Chi1v": {"command": ["Chi1v"], "column_names": ["_feat_Chi1v"]},
        "Chi2n": {"command": ["Chi2n"], "column_names": ["_feat_Chi2n"]},
        "Chi2v": {"command": ["Chi2v"], "column_names": ["_feat_Chi2v"]},
        "Chi3n": {"command": ["Chi3n"], "column_names": ["_feat_Chi3n"]},
        "Chi3v": {"command": ["Chi3v"], "column_names": ["_feat_Chi3v"]},
        "Chi4n": {"command": ["Chi4n"], "column_names": ["_feat_Chi4n"]},
        "Chi4v": {"command": ["Chi4v"], "column_names": ["_feat_Chi4v"]},
        "HallKierAlpha": {
            "command": ["HallKierAlpha"],
            "column_names": ["_feat_HallKierAlpha"],
        },
        "Ipc": {"command": ["Ipc"], "column_names": ["_feat_Ipc"]},
        "Kappa1": {"command": ["Kappa1"], "column_names": ["_feat_Kappa1"]},
        "Kappa2": {"command": ["Kappa2"], "column_names": ["_feat_Kappa2"]},
        "Kappa3": {"command": ["Kappa3"], "column_names": ["_feat_Kappa3"]},
        "LabuteASA": {"command": ["LabuteASA"], "column_names": ["_feat_LabuteASA"]},
        "PEOE_VSA1": {"command": ["PEOE_VSA1"], "column_names": ["_feat_PEOE_VSA1"]},
        "PEOE_VSA10": {"command": ["PEOE_VSA10"], "column_names": ["_feat_PEOE_VSA10"]},
        "PEOE_VSA11": {"command": ["PEOE_VSA11"], "column_names": ["_feat_PEOE_VSA11"]},
        "PEOE_VSA12": {"command": ["PEOE_VSA12"], "column_names": ["_feat_PEOE_VSA12"]},
        "PEOE_VSA13": {"command": ["PEOE_VSA13"], "column_names": ["_feat_PEOE_VSA13"]},
        "PEOE_VSA14": {"command": ["PEOE_VSA14"], "column_names": ["_feat_PEOE_VSA14"]},
        "PEOE_VSA2": {"command": ["PEOE_VSA2"], "column_names": ["_feat_PEOE_VSA2"]},
        "PEOE_VSA3": {"command": ["PEOE_VSA3"], "column_names": ["_feat_PEOE_VSA3"]},
        "PEOE_VSA4": {"command": ["PEOE_VSA4"], "column_names": ["_feat_PEOE_VSA4"]},
        "PEOE_VSA5": {"command": ["PEOE_VSA5"], "column_names": ["_feat_PEOE_VSA5"]},
        "PEOE_VSA6": {"command": ["PEOE_VSA6"], "column_names": ["_feat_PEOE_VSA6"]},
        "PEOE_VSA7": {"command": ["PEOE_VSA7"], "column_names": ["_feat_PEOE_VSA7"]},
        "PEOE_VSA8": {"command": ["PEOE_VSA8"], "column_names": ["_feat_PEOE_VSA8"]},
        "PEOE_VSA9": {"command": ["PEOE_VSA9"], "column_names": ["_feat_PEOE_VSA9"]},
        "SMR_VSA1": {"command": ["SMR_VSA1"], "column_names": ["_feat_SMR_VSA1"]},
        "SMR_VSA10": {"command": ["SMR_VSA10"], "column_names": ["_feat_SMR_VSA10"]},
        "SMR_VSA2": {"command": ["SMR_VSA2"], "column_names": ["_feat_SMR_VSA2"]},
        "SMR_VSA3": {"command": ["SMR_VSA3"], "column_names": ["_feat_SMR_VSA3"]},
        "SMR_VSA4": {"command": ["SMR_VSA4"], "column_names": ["_feat_SMR_VSA4"]},
        "SMR_VSA5": {"command": ["SMR_VSA5"], "column_names": ["_feat_SMR_VSA5"]},
        "SMR_VSA6": {"command": ["SMR_VSA6"], "column_names": ["_feat_SMR_VSA6"]},
        "SMR_VSA7": {"command": ["SMR_VSA7"], "column_names": ["_feat_SMR_VSA7"]},
        "SMR_VSA8": {"command": ["SMR_VSA8"], "column_names": ["_feat_SMR_VSA8"]},
        "SMR_VSA9": {"command": ["SMR_VSA9"], "column_names": ["_feat_SMR_VSA9"]},
        "SlogP_VSA1": {"command": ["SlogP_VSA1"], "column_names": ["_feat_SlogP_VSA1"]},
        "SlogP_VSA10": {
            "command": ["SlogP_VSA10"],
            "column_names": ["_feat_SlogP_VSA10"],
        },
        "SlogP_VSA11": {
            "command": ["SlogP_VSA11"],
            "column_names": ["_feat_SlogP_VSA11"],
        },
        "SlogP_VSA12": {
            "command": ["SlogP_VSA12"],
            "column_names": ["_feat_SlogP_VSA12"],
        },
        "SlogP_VSA2": {"command": ["SlogP_VSA2"], "column_names": ["_feat_SlogP_VSA2"]},
        "SlogP_VSA3": {"command": ["SlogP_VSA3"], "column_names": ["_feat_SlogP_VSA3"]},
        "SlogP_VSA4": {"command": ["SlogP_VSA4"], "column_names": ["_feat_SlogP_VSA4"]},
        "SlogP_VSA5": {"command": ["SlogP_VSA5"], "column_names": ["_feat_SlogP_VSA5"]},
        "SlogP_VSA6": {"command": ["SlogP_VSA6"], "column_names": ["_feat_SlogP_VSA6"]},
        "SlogP_VSA7": {"command": ["SlogP_VSA7"], "column_names": ["_feat_SlogP_VSA7"]},
        "SlogP_VSA8": {"command": ["SlogP_VSA8"], "column_names": ["_feat_SlogP_VSA8"]},
        "SlogP_VSA9": {"command": ["SlogP_VSA9"], "column_names": ["_feat_SlogP_VSA9"]},
        "TPSA": {"command": ["TPSA"], "column_names": ["_feat_TPSA"]},
        "EState_VSA1": {
            "command": ["EState_VSA1"],
            "column_names": ["_feat_EState_VSA1"],
        },
        "EState_VSA10": {
            "command": ["EState_VSA10"],
            "column_names": ["_feat_EState_VSA10"],
        },
        "EState_VSA11": {
            "command": ["EState_VSA11"],
            "column_names": ["_feat_EState_VSA11"],
        },
        "EState_VSA2": {
            "command": ["EState_VSA2"],
            "column_names": ["_feat_EState_VSA2"],
        },
        "EState_VSA3": {
            "command": ["EState_VSA3"],
            "column_names": ["_feat_EState_VSA3"],
        },
        "EState_VSA4": {
            "command": ["EState_VSA4"],
            "column_names": ["_feat_EState_VSA4"],
        },
        "EState_VSA5": {
            "command": ["EState_VSA5"],
            "column_names": ["_feat_EState_VSA5"],
        },
        "EState_VSA6": {
            "command": ["EState_VSA6"],
            "column_names": ["_feat_EState_VSA6"],
        },
        "EState_VSA7": {
            "command": ["EState_VSA7"],
            "column_names": ["_feat_EState_VSA7"],
        },
        "EState_VSA8": {
            "command": ["EState_VSA8"],
            "column_names": ["_feat_EState_VSA8"],
        },
        "EState_VSA9": {
            "command": ["EState_VSA9"],
            "column_names": ["_feat_EState_VSA9"],
        },
        "VSA_EState1": {
            "command": ["VSA_EState1"],
            "column_names": ["_feat_VSA_EState1"],
        },
        "VSA_EState10": {
            "command": ["VSA_EState10"],
            "column_names": ["_feat_VSA_EState10"],
        },
        "VSA_EState2": {
            "command": ["VSA_EState2"],
            "column_names": ["_feat_VSA_EState2"],
        },
        "VSA_EState3": {
            "command": ["VSA_EState3"],
            "column_names": ["_feat_VSA_EState3"],
        },
        "VSA_EState4": {
            "command": ["VSA_EState4"],
            "column_names": ["_feat_VSA_EState4"],
        },
        "VSA_EState5": {
            "command": ["VSA_EState5"],
            "column_names": ["_feat_VSA_EState5"],
        },
        "VSA_EState6": {
            "command": ["VSA_EState6"],
            "column_names": ["_feat_VSA_EState6"],
        },
        "VSA_EState7": {
            "command": ["VSA_EState7"],
            "column_names": ["_feat_VSA_EState7"],
        },
        "VSA_EState8": {
            "command": ["VSA_EState8"],
            "column_names": ["_feat_VSA_EState8"],
        },
        "VSA_EState9": {
            "command": ["VSA_EState9"],
            "column_names": ["_feat_VSA_EState9"],
        },
        "FractionCSP3": {
            "command": ["FractionCSP3"],
            "column_names": ["_feat_FractionCSP3"],
        },
        "HeavyAtomCount": {
            "command": ["HeavyAtomCount"],
            "column_names": ["_feat_HeavyAtomCount"],
        },
        "NHOHCount": {"command": ["NHOHCount"], "column_names": ["_feat_NHOHCount"]},
        "NOCount": {"command": ["NOCount"], "column_names": ["_feat_NOCount"]},
        "NumAliphaticCarbocycles": {
            "command": ["NumAliphaticCarbocycles"],
            "column_names": ["_feat_NumAliphaticCarbocycles"],
        },
        "NumAliphaticHeterocycles": {
            "command": ["NumAliphaticHeterocycles"],
            "column_names": ["_feat_NumAliphaticHeterocycles"],
        },
        "NumAliphaticRings": {
            "command": ["NumAliphaticRings"],
            "column_names": ["_feat_NumAliphaticRings"],
        },
        "NumAromaticCarbocycles": {
            "command": ["NumAromaticCarbocycles"],
            "column_names": ["_feat_NumAromaticCarbocycles"],
        },
        "NumAromaticHeterocycles": {
            "command": ["NumAromaticHeterocycles"],
            "column_names": ["_feat_NumAromaticHeterocycles"],
        },
        "NumAromaticRings": {
            "command": ["NumAromaticRings"],
            "column_names": ["_feat_NumAromaticRings"],
        },
        "NumHAcceptors": {
            "command": ["NumHAcceptors"],
            "column_names": ["_feat_NumHAcceptors"],
        },
        "NumHDonors": {"command": ["NumHDonors"], "column_names": ["_feat_NumHDonors"]},
        "NumHeteroatoms": {
            "command": ["NumHeteroatoms"],
            "column_names": ["_feat_NumHeteroatoms"],
        },
        "NumRotatableBonds": {
            "command": ["NumRotatableBonds"],
            "column_names": ["_feat_NumRotatableBonds"],
        },
        "NumSaturatedCarbocycles": {
            "command": ["NumSaturatedCarbocycles"],
            "column_names": ["_feat_NumSaturatedCarbocycles"],
        },
        "NumSaturatedHeterocycles": {
            "command": ["NumSaturatedHeterocycles"],
            "column_names": ["_feat_NumSaturatedHeterocycles"],
        },
        "NumSaturatedRings": {
            "command": ["NumSaturatedRings"],
            "column_names": ["_feat_NumSaturatedRings"],
        },
        "RingCount": {"command": ["RingCount"], "column_names": ["_feat_RingCount"]},
        "MolLogP": {"command": ["MolLogP"], "column_names": ["_feat_MolLogP"]},
        "MolMR": {"command": ["MolMR"], "column_names": ["_feat_MolMR"]},
        "fr_Al_COO": {"command": ["fr_Al_COO"], "column_names": ["_feat_fr_Al_COO"]},
        "fr_Al_OH": {"command": ["fr_Al_OH"], "column_names": ["_feat_fr_Al_OH"]},
        "fr_Al_OH_noTert": {
            "command": ["fr_Al_OH_noTert"],
            "column_names": ["_feat_fr_Al_OH_noTert"],
        },
        "fr_ArN": {"command": ["fr_ArN"], "column_names": ["_feat_fr_ArN"]},
        "fr_Ar_COO": {"command": ["fr_Ar_COO"], "column_names": ["_feat_fr_Ar_COO"]},
        "fr_Ar_N": {"command": ["fr_Ar_N"], "column_names": ["_feat_fr_Ar_N"]},
        "fr_Ar_NH": {"command": ["fr_Ar_NH"], "column_names": ["_feat_fr_Ar_NH"]},
        "fr_Ar_OH": {"command": ["fr_Ar_OH"], "column_names": ["_feat_fr_Ar_OH"]},
        "fr_COO": {"command": ["fr_COO"], "column_names": ["_feat_fr_COO"]},
        "fr_COO2": {"command": ["fr_COO2"], "column_names": ["_feat_fr_COO2"]},
        "fr_C_O": {"command": ["fr_C_O"], "column_names": ["_feat_fr_C_O"]},
        "fr_C_O_noCOO": {
            "command": ["fr_C_O_noCOO"],
            "column_names": ["_feat_fr_C_O_noCOO"],
        },
        "fr_C_S": {"command": ["fr_C_S"], "column_names": ["_feat_fr_C_S"]},
        "fr_HOCCN": {"command": ["fr_HOCCN"], "column_names": ["_feat_fr_HOCCN"]},
        "fr_Imine": {"command": ["fr_Imine"], "column_names": ["_feat_fr_Imine"]},
        "fr_NH0": {"command": ["fr_NH0"], "column_names": ["_feat_fr_NH0"]},
        "fr_NH1": {"command": ["fr_NH1"], "column_names": ["_feat_fr_NH1"]},
        "fr_NH2": {"command": ["fr_NH2"], "column_names": ["_feat_fr_NH2"]},
        "fr_N_O": {"command": ["fr_N_O"], "column_names": ["_feat_fr_N_O"]},
        "fr_Ndealkylation1": {
            "command": ["fr_Ndealkylation1"],
            "column_names": ["_feat_fr_Ndealkylation1"],
        },
        "fr_Ndealkylation2": {
            "command": ["fr_Ndealkylation2"],
            "column_names": ["_feat_fr_Ndealkylation2"],
        },
        "fr_Nhpyrrole": {
            "command": ["fr_Nhpyrrole"],
            "column_names": ["_feat_fr_Nhpyrrole"],
        },
        "fr_SH": {"command": ["fr_SH"], "column_names": ["_feat_fr_SH"]},
        "fr_aldehyde": {
            "command": ["fr_aldehyde"],
            "column_names": ["_feat_fr_aldehyde"],
        },
        "fr_alkyl_carbamate": {
            "command": ["fr_alkyl_carbamate"],
            "column_names": ["_feat_fr_alkyl_carbamate"],
        },
        "fr_alkyl_halide": {
            "command": ["fr_alkyl_halide"],
            "column_names": ["_feat_fr_alkyl_halide"],
        },
        "fr_allylic_oxid": {
            "command": ["fr_allylic_oxid"],
            "column_names": ["_feat_fr_allylic_oxid"],
        },
        "fr_amide": {"command": ["fr_amide"], "column_names": ["_feat_fr_amide"]},
        "fr_amidine": {"command": ["fr_amidine"], "column_names": ["_feat_fr_amidine"]},
        "fr_aniline": {"command": ["fr_aniline"], "column_names": ["_feat_fr_aniline"]},
        "fr_aryl_methyl": {
            "command": ["fr_aryl_methyl"],
            "column_names": ["_feat_fr_aryl_methyl"],
        },
        "fr_azide": {"command": ["fr_azide"], "column_names": ["_feat_fr_azide"]},
        "fr_azo": {"command": ["fr_azo"], "column_names": ["_feat_fr_azo"]},
        "fr_barbitur": {
            "command": ["fr_barbitur"],
            "column_names": ["_feat_fr_barbitur"],
        },
        "fr_benzene": {"command": ["fr_benzene"], "column_names": ["_feat_fr_benzene"]},
        "fr_benzodiazepine": {
            "command": ["fr_benzodiazepine"],
            "column_names": ["_feat_fr_benzodiazepine"],
        },
        "fr_bicyclic": {
            "command": ["fr_bicyclic"],
            "column_names": ["_feat_fr_bicyclic"],
        },
        "fr_diazo": {"command": ["fr_diazo"], "column_names": ["_feat_fr_diazo"]},
        "fr_dihydropyridine": {
            "command": ["fr_dihydropyridine"],
            "column_names": ["_feat_fr_dihydropyridine"],
        },
        "fr_epoxide": {"command": ["fr_epoxide"], "column_names": ["_feat_fr_epoxide"]},
        "fr_ester": {"command": ["fr_ester"], "column_names": ["_feat_fr_ester"]},
        "fr_ether": {"command": ["fr_ether"], "column_names": ["_feat_fr_ether"]},
        "fr_furan": {"command": ["fr_furan"], "column_names": ["_feat_fr_furan"]},
        "fr_guanido": {"command": ["fr_guanido"], "column_names": ["_feat_fr_guanido"]},
        "fr_halogen": {"command": ["fr_halogen"], "column_names": ["_feat_fr_halogen"]},
        "fr_hdrzine": {"command": ["fr_hdrzine"], "column_names": ["_feat_fr_hdrzine"]},
        "fr_hdrzone": {"command": ["fr_hdrzone"], "column_names": ["_feat_fr_hdrzone"]},
        "fr_imidazole": {
            "command": ["fr_imidazole"],
            "column_names": ["_feat_fr_imidazole"],
        },
        "fr_imide": {"command": ["fr_imide"], "column_names": ["_feat_fr_imide"]},
        "fr_isocyan": {"command": ["fr_isocyan"], "column_names": ["_feat_fr_isocyan"]},
        "fr_isothiocyan": {
            "command": ["fr_isothiocyan"],
            "column_names": ["_feat_fr_isothiocyan"],
        },
        "fr_ketone": {"command": ["fr_ketone"], "column_names": ["_feat_fr_ketone"]},
        "fr_ketone_Topliss": {
            "command": ["fr_ketone_Topliss"],
            "column_names": ["_feat_fr_ketone_Topliss"],
        },
        "fr_lactam": {"command": ["fr_lactam"], "column_names": ["_feat_fr_lactam"]},
        "fr_lactone": {"command": ["fr_lactone"], "column_names": ["_feat_fr_lactone"]},
        "fr_methoxy": {"command": ["fr_methoxy"], "column_names": ["_feat_fr_methoxy"]},
        "fr_morpholine": {
            "command": ["fr_morpholine"],
            "column_names": ["_feat_fr_morpholine"],
        },
        "fr_nitrile": {"command": ["fr_nitrile"], "column_names": ["_feat_fr_nitrile"]},
        "fr_nitro": {"command": ["fr_nitro"], "column_names": ["_feat_fr_nitro"]},
        "fr_nitro_arom": {
            "command": ["fr_nitro_arom"],
            "column_names": ["_feat_fr_nitro_arom"],
        },
        "fr_nitro_arom_nonortho": {
            "command": ["fr_nitro_arom_nonortho"],
            "column_names": ["_feat_fr_nitro_arom_nonortho"],
        },
        "fr_nitroso": {"command": ["fr_nitroso"], "column_names": ["_feat_fr_nitroso"]},
        "fr_oxazole": {"command": ["fr_oxazole"], "column_names": ["_feat_fr_oxazole"]},
        "fr_oxime": {"command": ["fr_oxime"], "column_names": ["_feat_fr_oxime"]},
        "fr_para_hydroxylation": {
            "command": ["fr_para_hydroxylation"],
            "column_names": ["_feat_fr_para_hydroxylation"],
        },
        "fr_phenol": {"command": ["fr_phenol"], "column_names": ["_feat_fr_phenol"]},
        "fr_phenol_noOrthoHbond": {
            "command": ["fr_phenol_noOrthoHbond"],
            "column_names": ["_feat_fr_phenol_noOrthoHbond"],
        },
        "fr_phos_acid": {
            "command": ["fr_phos_acid"],
            "column_names": ["_feat_fr_phos_acid"],
        },
        "fr_phos_ester": {
            "command": ["fr_phos_ester"],
            "column_names": ["_feat_fr_phos_ester"],
        },
        "fr_piperdine": {
            "command": ["fr_piperdine"],
            "column_names": ["_feat_fr_piperdine"],
        },
        "fr_piperzine": {
            "command": ["fr_piperzine"],
            "column_names": ["_feat_fr_piperzine"],
        },
        "fr_priamide": {
            "command": ["fr_priamide"],
            "column_names": ["_feat_fr_priamide"],
        },
        "fr_prisulfonamd": {
            "command": ["fr_prisulfonamd"],
            "column_names": ["_feat_fr_prisulfonamd"],
        },
        "fr_pyridine": {
            "command": ["fr_pyridine"],
            "column_names": ["_feat_fr_pyridine"],
        },
        "fr_quatN": {"command": ["fr_quatN"], "column_names": ["_feat_fr_quatN"]},
        "fr_sulfide": {"command": ["fr_sulfide"], "column_names": ["_feat_fr_sulfide"]},
        "fr_sulfonamd": {
            "command": ["fr_sulfonamd"],
            "column_names": ["_feat_fr_sulfonamd"],
        },
        "fr_sulfone": {"command": ["fr_sulfone"], "column_names": ["_feat_fr_sulfone"]},
        "fr_term_acetylene": {
            "command": ["fr_term_acetylene"],
            "column_names": ["_feat_fr_term_acetylene"],
        },
        "fr_tetrazole": {
            "command": ["fr_tetrazole"],
            "column_names": ["_feat_fr_tetrazole"],
        },
        "fr_thiazole": {
            "command": ["fr_thiazole"],
            "column_names": ["_feat_fr_thiazole"],
        },
        "fr_thiocyan": {
            "command": ["fr_thiocyan"],
            "column_names": ["_feat_fr_thiocyan"],
        },
        "fr_thiophene": {
            "command": ["fr_thiophene"],
            "column_names": ["_feat_fr_thiophene"],
        },
        "fr_unbrch_alkane": {
            "command": ["fr_unbrch_alkane"],
            "column_names": ["_feat_fr_unbrch_alkane"],
        },
        "fr_urea": {"command": ["fr_urea"], "column_names": ["_feat_fr_urea"]},
    }
}
